### ISSUE TITLE
Homebrew formula

### ISSUE THREAD

**Issue by oncletom** [bbcrd/audiowaveform#21]
As @chrisn mentioned during a conversation this morning, a nice way to ease the OSX install would be to provide a `homebrew` formula.

**Comment by renatoargh** [comment]
+1

**Comment by oncletom** [comment]
@renatoargh is it something you would be able to do?

**Comment by renatoargh** [comment]
Unfortunately I have limited knowledge in this area. I would love to help, since `audiowaveform` is amazing.

**Comment by chrisn** [comment]
Homebrew formula is now available [here](https://github.com/bbcrd/homebrew-audiowaveform), and also described in the [ReadMe](https://github.com/bbcrd/audiowaveform/blob/master/README.md).
