### ISSUE TITLE
Question: 22,050 sample rate

### ISSUE THREAD

**Issue by nikolasleblanc** [bbcrd/audiowaveform#29]
Hey, hope this isn't a stupid question, but I'm generating dat files from a podcast with a 22,050 sample rate. The output of audiowaveform when creating the dat file says 44,100:

```
Input file: a.mp3
Format: Audio MPEG layer I stream
Bit rate: 25000 kbit/s
CRC: no
Mode: single channel
Emphasis: no
Sample rate: 44100 Hz
Generating waveform data...
Samples per pixel: 256
Input channels: 1
```

Naturally, when I make a png from the dat file, the waveform only occupies half of the space. Any tips on what I'm doing wrong - or how to set the sample rate explicitly?

Many thanks.

**Comment by chrisn** [comment]
Hi Nikolas,

The audiowaveform output says that the bit rate (which is the data rate after mp3 compression) is 25,000 kbit/s, and the audio sample rate is 44,100 Hz. Are you sure the audio sample rate of your file is 22,050 Hz? I'd be happy to take a look at the file, if you can upload it somewhere or email it to me.

Chris

**Comment by nikolasleblanc** [comment]
Hey Chris, thanks a lot for looking into this for me. The file I'm using as a sample is from a podcast I listen to, and can be downloaded here:

http://traffic.libsyn.com/wtfpod/WTF_-_EPISODE_584_CHRIS_DELIA.mp3

When I run "Get Info" on the file from my mac, it reports a sample rate of 22,050, so not sure what's up. Here's a screen cap:

![sample_mp3_info_and_question__22_050_sample_rate_ _issue__29_ _bbcrd_audiowaveform](https://cloud.githubusercontent.com/assets/1944954/7447899/0a312570-f1d9-11e4-94ba-f2faa365bdee.jpg)

Thanks again, very much appreciate your help with this!

Nik

**Comment by chrisn** [comment]
I ran your file through audiowaveform on my machine using this command:

    $ audiowaveform -i WTF_-_EPISODE_584_CHRIS_DELIA.mp3 -o test.dat -z 256 -b 8

with the following output:

    Input file: WTF_-_EPISODE_584_CHRIS_DELIA.mp3
    Format: Audio MPEG layer III stream
    Bit rate: 40000 kbit/s
    CRC: no
    Mode: single channel
    Emphasis: no
    Sample rate: 22050 Hz
    Generating waveform data...
    Samples per pixel: 256
    Input channels: 1
    Done: 100%
    Frames decoded: 193374 (84:11.402)
    Generated 435092 points
    Writing output file: test.dat
    Resolution: 8 bits

The sample rate is reported as 22,050 Hz, which looks OK. I notice that the format is reported as layer III, as I'd expect for an MP3 file, but your a.mp3 file is reported as layer I. I haven't tested audiowaveform with layer I files, so it's possible it doesn't handle them correctly. Would you be able to share the file with me, to test?

**Comment by nikolasleblanc** [comment]
Hey Chris, here's a link to the a.mp3 sample file I was using - it's just the same podcast file but renamed, but still worth a shot.

Interesting to note, I ran the exact command you listed against the exact mp3 you tested it against, and I got the following output:

![1__nikolas_nikolass-macbook-pro____desktop__zsh_](https://cloud.githubusercontent.com/assets/1944954/7474194/c0ecc578-f30d-11e4-840e-c2053afd3087.jpg)

Which leads me to believe that this may have something to do with my install of audio waveform. I followed the instructions, but I wanted to point out I'm running it on a mac, having installed required libraries via brew when required.

For comparisons sake, this is the output I get when running audio waveform against a.mp3:

![1__nikolas_nikolass-macbook-pro____desktop__zsh_](https://cloud.githubusercontent.com/assets/1944954/7474235/00d7a798-f30e-11e4-918c-0940cc8b33fa.jpg)

When I get a free minute today, I'll try installing audio waveform on a vagrant box ubuntu and see if I get more appropriate results - but in the meantime, this output should at least help you confirm this is a product with my build and not your library.

**Comment by nikolasleblanc** [comment]
And the link to the a.mp3 file:

https://www.dropbox.com/s/a3udggprtd8v6sw/a.mp3?dl=0

**Comment by chrisn** [comment]
Yes, this looks like an issue with your build. I don't see any of those 'lost synchronization' errors when I run the program on Ubuntu. I suspect the problem is with the [libmad](http://www.underbit.com/products/mad/) library, but I'm not a Mac user so I can't offer any help.

**Comment by oncletom** [comment]
I can give a go later on today to see if I can reproduce.

**Comment by nikolasleblanc** [comment]
Hey guys, thanks for all the help. I installed audiowaveform on a vagrant ubuntu box and everything worked as expected. Can confirm that this was an issue with my build. @chrisn, you're free to close.

```
vagrant@precise32:/var/www$ audiowaveform -i a.mp3 -o test.dat -z 256 -b 8
Input file: a.mp3
Format: Audio MPEG layer III stream
Bit rate: 40000 kbit/s
CRC: no
Mode: single channel
Emphasis: no
Sample rate: 22050 Hz
Generating waveform data...
Samples per pixel: 256
Input channels: 1
Done: 100%
Frames decoded: 193374 (84:11.402)
Generated 435092 points
Writing output file: test.dat
Resolution: 8 bits
```

@oncletom, let me know if you run into the same problems that I did on your mac build.

Thanks.
