### ISSUE TITLE
Convert to data client side

### ISSUE THREAD

**Issue by tgoldenberg** [bbcrd/audiowaveform#31]
Hi, this seems like a very interesting project. I am interested in converting mp3 files and user recorded .caf files on a React Native iOS app into data visualizations. From what I gather, this project converts audio files to data through command line tools. Is there a way I could convert the files on the client side with JavaScript? Any suggestions or pointers would be greatly appreciated. 

Thanks!

**Comment by chrisn** [comment]
I imagine you could wrap some of the audiowaveform code as a native module in React (see [here](https://facebook.github.io/react-native/docs/native-modules-ios.html)) to be invoked from JavaScript, but you'd have to write your own code to handle the Core Audio Format files, as audiowaveform only handles MP3, WAV, and FLAC audio.

**Comment by oncletom** [comment]
@tgoldenberg we use the WebAudio API to convert MP3 into waveforms but this is not suited to a native app. You probably want to use [iOS Audio API](https://developer.apple.com/library/ios/documentation/AudioVideo/Conceptual/MultimediaPG/UsingAudio/UsingAudio.html) and then interface it with Peaks.js to visualise it into a canvas – but there are probably more optimised ways of doing it.
