### ISSUE TITLE
Is there a way to output data objects divided by 100?

### ISSUE THREAD

**Issue by drhouse7** [bbcrd/audiowaveform#42]
Hi,
I tried to use Audiowaveform to generate JSON, the output is something like

`{ ... "data":[0,0,0,0,-46,37 ...`

Instead I would like to output data objects divided by 100.
Is there a built in option or something I can do for this? (reading the doc and searching the web I couldn't find it)

Best regards

**Comment by Joshfindit** [comment]
Since you're generating JavaScript anyway (JSON), it would be trivial to use JavaScript (or another JSON-friendly language) to divide those numbers and update the file.

**Comment by drhouse7** [comment]
@Joshfindit 
Yes on PHP I can use array_map but I was asking here if there is a better solution

**Comment by chrisn** [comment]
audiowaveform can generate output data with two different scales: 8-bit (-128 to +127) or 16-bit (-32768 to +32767) - see the file format documentation [here](https://github.com/bbcrd/audiowaveform/blob/master/doc/DataFormat.md). There isn't currently an option to specify your own scaling.
